### ISSUE TITLE
Risk: over-authorization of AWS IoT policy

### ISSUE THREAD

**Issue by P-Verifier** [aws-samples/aws-iot-device-management-workshop#5]
We are a security research team and we recently discovered that there is an over-authorization security issue with this project's IoT policy.
The affected file is as following:

	1. aws-iot-device-management-workshop/cfn/cfn-iot-dm-w.json

**Comment by psachaamazon** [comment]
The permissive policy is for ease of use of the workshop. Added related note to the documentation.
